services:

  app:
    build: ./app
    container_name: crud-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: crud_alunos
    volumes:
      - ./app/src:/var/www/html
    depends_on:
      - db
    networks:
      - crud-network

  db:
    image: mysql:8.0
    container_name: crud-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_alunos
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crud-network

volumes:
  db_data:

networks:
  crud-network:
    driver: bridge